### ISSUE TITLE
Error: couldn't read GenesisDoc

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/wordle#1]
I cannot start my wordle chain because the genesis file is not generated/wrong path . 

I am following this tutorial https://docs.celestia.org/developers/run-wordle

After running `ignite chain build`  i get this: 
´´´
Cosmos SDK's version is: stargate - v0.45.4

🛠️  Building proto...
📦 Installing dependencies...
🛠️  Building the blockchain...
🗃  Installed. Use with: wordled

```

I am running a celestia light client locally with `celestia light start --core.grpc https://rpc-mamaki.pops.one:9090`

I am trying to start a chain with: 
```bash
wordled start --optimint.aggregator true --optimint.da_layer celestia --optimint.da_config='{"base_url":"http://127.0.0.1:26658","timeout":60000000000,"gas_limit":6000000,"namespace_id":[0,0,0,0,0,0,255,255]}' --optimint.namespace_id 000000000000FFFF --optimint.da_start_height 21380
```

I get the following error:
```
3:34PM INF starting node with ABCI Optimint in-process
Error: couldn't read GenesisDoc file: open /home/nashqueue/.wordle/config/genesis.json: no such file or directory
Usage:
  wordled start [flags]

Flags: 
  <List of Flags here.....>
```

After following the Tutorial this is my current state: 
https://github.com/nashqueue/celestia-wordle-tutorial

I am using Windows 10 with wsl2 Linux Subsystem. The other ignite cli tutorials had no problems. 
@Bidon15 tried to execute my wordle repo and there was no genesis file generated for him as well. He is using Ubuntu 20.

**Comment by Bidon15** [comment]
True. I've tried to follow the doc using my ubuntu droplet and got to the same outcome as described in the issue

**Comment by nashqueue** [comment]
Solved by running `iginite chain serve` instead of build and then ctrl+C to stop the chain. This will create the needed genesis file.
